/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    /// <summary>
    /// LocalizationMapModel
    /// </summary>
    [DataContract(Name = "LocalizationMapModel")]
    public partial class LocalizationMapModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMapModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LocalizationMapModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMapModel" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="active">active (required).</param>
        /// <param name="lighting">lighting (required).</param>
        /// <param name="color">color (required).</param>
        /// <param name="positionX">positionX (required).</param>
        /// <param name="positionY">positionY (required).</param>
        /// <param name="positionZ">positionZ (required).</param>
        /// <param name="rotationX">rotationX (required).</param>
        /// <param name="rotationY">rotationY (required).</param>
        /// <param name="rotationZ">rotationZ (required).</param>
        /// <param name="rotationW">rotationW (required).</param>
        /// <param name="localInputImagePositions">localInputImagePositions.</param>
        public LocalizationMapModel(Guid id = default, string name = default, bool active = default, int lighting = default, int color = default, double positionX = default, double positionY = default, double positionZ = default, double rotationX = default, double rotationY = default, double rotationZ = default, double rotationW = default, List<double> localInputImagePositions = default)
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for LocalizationMapModel and cannot be null");
            }
            this.Name = name;
            this.Active = active;
            this.Lighting = lighting;
            this.Color = color;
            this.PositionX = positionX;
            this.PositionY = positionY;
            this.PositionZ = positionZ;
            this.RotationX = rotationX;
            this.RotationY = rotationY;
            this.RotationZ = rotationZ;
            this.RotationW = rotationW;
            this.LocalInputImagePositions = localInputImagePositions;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name = "active", IsRequired = true, EmitDefaultValue = true)]
        public bool Active { get; set; }

        /// <summary>
        /// Gets or Sets Lighting
        /// </summary>
        [DataMember(Name = "lighting", IsRequired = true, EmitDefaultValue = true)]
        public int Lighting { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [DataMember(Name = "color", IsRequired = true, EmitDefaultValue = true)]
        public int Color { get; set; }

        /// <summary>
        /// Gets or Sets PositionX
        /// </summary>
        [DataMember(Name = "positionX", IsRequired = true, EmitDefaultValue = true)]
        public double PositionX { get; set; }

        /// <summary>
        /// Gets or Sets PositionY
        /// </summary>
        [DataMember(Name = "positionY", IsRequired = true, EmitDefaultValue = true)]
        public double PositionY { get; set; }

        /// <summary>
        /// Gets or Sets PositionZ
        /// </summary>
        [DataMember(Name = "positionZ", IsRequired = true, EmitDefaultValue = true)]
        public double PositionZ { get; set; }

        /// <summary>
        /// Gets or Sets RotationX
        /// </summary>
        [DataMember(Name = "rotationX", IsRequired = true, EmitDefaultValue = true)]
        public double RotationX { get; set; }

        /// <summary>
        /// Gets or Sets RotationY
        /// </summary>
        [DataMember(Name = "rotationY", IsRequired = true, EmitDefaultValue = true)]
        public double RotationY { get; set; }

        /// <summary>
        /// Gets or Sets RotationZ
        /// </summary>
        [DataMember(Name = "rotationZ", IsRequired = true, EmitDefaultValue = true)]
        public double RotationZ { get; set; }

        /// <summary>
        /// Gets or Sets RotationW
        /// </summary>
        [DataMember(Name = "rotationW", IsRequired = true, EmitDefaultValue = true)]
        public double RotationW { get; set; }

        /// <summary>
        /// Gets or Sets LocalInputImagePositions
        /// </summary>
        [DataMember(Name = "localInputImagePositions", EmitDefaultValue = true)]
        public List<double> LocalInputImagePositions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LocalizationMapModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Lighting: ").Append(Lighting).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  PositionX: ").Append(PositionX).Append("\n");
            sb.Append("  PositionY: ").Append(PositionY).Append("\n");
            sb.Append("  PositionZ: ").Append(PositionZ).Append("\n");
            sb.Append("  RotationX: ").Append(RotationX).Append("\n");
            sb.Append("  RotationY: ").Append(RotationY).Append("\n");
            sb.Append("  RotationZ: ").Append(RotationZ).Append("\n");
            sb.Append("  RotationW: ").Append(RotationW).Append("\n");
            sb.Append("  LocalInputImagePositions: ").Append(LocalInputImagePositions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
