/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    /// <summary>
    /// NodeModel
    /// </summary>
    [DataContract(Name = "NodeModel")]
    public partial class NodeModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NodeModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NodeModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NodeModel" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="active">active (required).</param>
        /// <param name="positionX">positionX (required).</param>
        /// <param name="positionY">positionY (required).</param>
        /// <param name="positionZ">positionZ (required).</param>
        /// <param name="rotationX">rotationX (required).</param>
        /// <param name="rotationY">rotationY (required).</param>
        /// <param name="rotationZ">rotationZ (required).</param>
        /// <param name="rotationW">rotationW (required).</param>
        /// <param name="labelType">labelType.</param>
        /// <param name="label">label.</param>
        /// <param name="linkType">linkType.</param>
        /// <param name="link">link.</param>
        /// <param name="labelScale">labelScale.</param>
        /// <param name="labelWidth">labelWidth.</param>
        /// <param name="labelHeight">labelHeight.</param>
        /// <param name="parent">parent.</param>
        /// <param name="layer">layer.</param>
        public NodeModel(Guid id = default, string name = default, DateTime? createdAt = default, bool active = default, double positionX = default, double positionY = default, double positionZ = default, double rotationX = default, double rotationY = default, double rotationZ = default, double rotationW = default, int? labelType = default, string label = default, int? linkType = default, string link = default, double? labelScale = default, double? labelWidth = default, double? labelHeight = default, Guid? parent = default, Guid? layer = default)
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for NodeModel and cannot be null");
            }
            this.Name = name;
            this.Active = active;
            this.PositionX = positionX;
            this.PositionY = positionY;
            this.PositionZ = positionZ;
            this.RotationX = rotationX;
            this.RotationY = rotationY;
            this.RotationZ = rotationZ;
            this.RotationW = rotationW;
            this.CreatedAt = createdAt;
            this.LabelType = labelType;
            this.Label = label;
            this.LinkType = linkType;
            this.Link = link;
            this.LabelScale = labelScale;
            this.LabelWidth = labelWidth;
            this.LabelHeight = labelHeight;
            this.Parent = parent;
            this.Layer = layer;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", EmitDefaultValue = true)]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [DataMember(Name = "active", IsRequired = true, EmitDefaultValue = true)]
        public bool Active { get; set; }

        /// <summary>
        /// Gets or Sets PositionX
        /// </summary>
        [DataMember(Name = "positionX", IsRequired = true, EmitDefaultValue = true)]
        public double PositionX { get; set; }

        /// <summary>
        /// Gets or Sets PositionY
        /// </summary>
        [DataMember(Name = "positionY", IsRequired = true, EmitDefaultValue = true)]
        public double PositionY { get; set; }

        /// <summary>
        /// Gets or Sets PositionZ
        /// </summary>
        [DataMember(Name = "positionZ", IsRequired = true, EmitDefaultValue = true)]
        public double PositionZ { get; set; }

        /// <summary>
        /// Gets or Sets RotationX
        /// </summary>
        [DataMember(Name = "rotationX", IsRequired = true, EmitDefaultValue = true)]
        public double RotationX { get; set; }

        /// <summary>
        /// Gets or Sets RotationY
        /// </summary>
        [DataMember(Name = "rotationY", IsRequired = true, EmitDefaultValue = true)]
        public double RotationY { get; set; }

        /// <summary>
        /// Gets or Sets RotationZ
        /// </summary>
        [DataMember(Name = "rotationZ", IsRequired = true, EmitDefaultValue = true)]
        public double RotationZ { get; set; }

        /// <summary>
        /// Gets or Sets RotationW
        /// </summary>
        [DataMember(Name = "rotationW", IsRequired = true, EmitDefaultValue = true)]
        public double RotationW { get; set; }

        /// <summary>
        /// Gets or Sets LabelType
        /// </summary>
        [DataMember(Name = "labelType", EmitDefaultValue = true)]
        public int? LabelType { get; set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [DataMember(Name = "label", EmitDefaultValue = true)]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets LinkType
        /// </summary>
        [DataMember(Name = "linkType", EmitDefaultValue = true)]
        public int? LinkType { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name = "link", EmitDefaultValue = true)]
        public string Link { get; set; }

        /// <summary>
        /// Gets or Sets LabelScale
        /// </summary>
        [DataMember(Name = "labelScale", EmitDefaultValue = true)]
        public double? LabelScale { get; set; }

        /// <summary>
        /// Gets or Sets LabelWidth
        /// </summary>
        [DataMember(Name = "labelWidth", EmitDefaultValue = true)]
        public double? LabelWidth { get; set; }

        /// <summary>
        /// Gets or Sets LabelHeight
        /// </summary>
        [DataMember(Name = "labelHeight", EmitDefaultValue = true)]
        public double? LabelHeight { get; set; }

        /// <summary>
        /// Gets or Sets Parent
        /// </summary>
        [DataMember(Name = "parent", EmitDefaultValue = true)]
        public Guid? Parent { get; set; }

        /// <summary>
        /// Gets or Sets Layer
        /// </summary>
        [DataMember(Name = "layer", EmitDefaultValue = true)]
        public Guid? Layer { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NodeModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  PositionX: ").Append(PositionX).Append("\n");
            sb.Append("  PositionY: ").Append(PositionY).Append("\n");
            sb.Append("  PositionZ: ").Append(PositionZ).Append("\n");
            sb.Append("  RotationX: ").Append(RotationX).Append("\n");
            sb.Append("  RotationY: ").Append(RotationY).Append("\n");
            sb.Append("  RotationZ: ").Append(RotationZ).Append("\n");
            sb.Append("  RotationW: ").Append(RotationW).Append("\n");
            sb.Append("  LabelType: ").Append(LabelType).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  LinkType: ").Append(LinkType).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  LabelScale: ").Append(LabelScale).Append("\n");
            sb.Append("  LabelWidth: ").Append(LabelWidth).Append("\n");
            sb.Append("  LabelHeight: ").Append(LabelHeight).Append("\n");
            sb.Append("  Parent: ").Append(Parent).Append("\n");
            sb.Append("  Layer: ").Append(Layer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
