from typing import Any

class MultipartParser:
    def __init__(self, boundary: str, charset: str) -> None: ...
    def write(self, chunk: bytes) -> None: ...
    @property
    def parts(self) -> list[Any]: ...
