/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Plerion.Client.FileParameter;
using OpenAPIDateConverter = Plerion.Client.OpenAPIDateConverter;

namespace Plerion.Model
{
    // fuck
    /// <summary>
    /// FullOpenCVCamera
    /// </summary>
    [DataContract(Name = "FullOpenCVCamera")]
    public partial class FullOpenCVCamera
    {
        /// <summary>
        /// Defines Mirroring
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MirroringEnum
        {
            /// <summary>
            /// Enum None for value: None
            /// </summary>
            [EnumMember(Value = "None")]
            None = 1,

            /// <summary>
            /// Enum X for value: X
            /// </summary>
            [EnumMember(Value = "X")]
            X = 2,

            /// <summary>
            /// Enum Y for value: Y
            /// </summary>
            [EnumMember(Value = "Y")]
            Y = 3
        }


        /// <summary>
        /// Gets or Sets Mirroring
        /// </summary>

        [DataMember(Name = "mirroring", IsRequired = true, EmitDefaultValue = true)]
        public MirroringEnum Mirroring
        {
            get{ return _Mirroring;}
            set
            {
                _Mirroring = value;
                _flagMirroring = true;
            }
        }
        private MirroringEnum _Mirroring;
        private bool _flagMirroring;

        /// <summary>
        /// Returns false as Mirroring should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMirroring()
        {
            return _flagMirroring;
        }
        /// <summary>
        /// Defines Rotation
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RotationEnum
        {
            /// <summary>
            /// Enum None for value: None
            /// </summary>
            [EnumMember(Value = "None")]
            None = 1,

            /// <summary>
            /// Enum _90CW for value: 90_CW
            /// </summary>
            [EnumMember(Value = "90_CW")]
            _90CW = 2,

            /// <summary>
            /// Enum _180 for value: 180
            /// </summary>
            [EnumMember(Value = "180")]
            _180 = 3,

            /// <summary>
            /// Enum _90CCW for value: 90_CCW
            /// </summary>
            [EnumMember(Value = "90_CCW")]
            _90CCW = 4
        }


        /// <summary>
        /// Gets or Sets Rotation
        /// </summary>

        [DataMember(Name = "rotation", IsRequired = true, EmitDefaultValue = true)]
        public RotationEnum Rotation
        {
            get{ return _Rotation;}
            set
            {
                _Rotation = value;
                _flagRotation = true;
            }
        }
        private RotationEnum _Rotation;
        private bool _flagRotation;

        /// <summary>
        /// Returns false as Rotation should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRotation()
        {
            return _flagRotation;
        }
        /// <summary>
        /// Defines Model
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ModelEnum
        {
            /// <summary>
            /// Enum FULLOPENCV for value: FULL_OPENCV
            /// </summary>
            [EnumMember(Value = "FULL_OPENCV")]
            FULLOPENCV = 1
        }


        /// <summary>
        /// Gets or Sets Model
        /// </summary>

        [DataMember(Name = "model", IsRequired = true, EmitDefaultValue = true)]
        public ModelEnum Model
        {
            get{ return _Model;}
            set
            {
                _Model = value;
                _flagModel = true;
            }
        }
        private ModelEnum _Model;
        private bool _flagModel;

        /// <summary>
        /// Returns false as Model should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeModel()
        {
            return _flagModel;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="FullOpenCVCamera" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FullOpenCVCamera() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FullOpenCVCamera" /> class.
        /// </summary>
        /// <param name="width">width (required).</param>
        /// <param name="height">height (required).</param>
        /// <param name="mirroring">mirroring (required).</param>
        /// <param name="rotation">rotation (required).</param>
        /// <param name="model">model (required).</param>
        /// <param name="fx">fx (required).</param>
        /// <param name="fy">fy (required).</param>
        /// <param name="cx">cx (required).</param>
        /// <param name="cy">cy (required).</param>
        /// <param name="k1">k1 (required).</param>
        /// <param name="k2">k2 (required).</param>
        /// <param name="p1">p1 (required).</param>
        /// <param name="p2">p2 (required).</param>
        /// <param name="k3">k3 (required).</param>
        /// <param name="k4">k4 (required).</param>
        /// <param name="k5">k5 (required).</param>
        /// <param name="k6">k6 (required).</param>
        public FullOpenCVCamera(int width, int height, MirroringEnum mirroring, RotationEnum rotation, ModelEnum model, double fx, double fy, double cx, double cy, double k1, double k2, double p1, double p2, double k3, double k4, double k5, double k6)
        {
            this.Width = width;
            this.Height = height;
            this.Mirroring = mirroring;
            this.Rotation = rotation;
            this.Model = model;
            this.Fx = fx;
            this.Fy = fy;
            this.Cx = cx;
            this.Cy = cy;
            this.K1 = k1;
            this.K2 = k2;
            this.P1 = p1;
            this.P2 = p2;
            this.K3 = k3;
            this.K4 = k4;
            this.K5 = k5;
            this.K6 = k6;
        }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "width", IsRequired = true, EmitDefaultValue = true)]
        public int Width
        {
            get{ return _Width;}
            set
            {
                _Width = value;
                _flagWidth = true;
            }
        }
        private int _Width;
        private bool _flagWidth;

        /// <summary>
        /// Returns false as Width should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeWidth()
        {
            return _flagWidth;
        }
        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", IsRequired = true, EmitDefaultValue = true)]
        public int Height
        {
            get{ return _Height;}
            set
            {
                _Height = value;
                _flagHeight = true;
            }
        }
        private int _Height;
        private bool _flagHeight;

        /// <summary>
        /// Returns false as Height should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeHeight()
        {
            return _flagHeight;
        }
        /// <summary>
        /// Gets or Sets Fx
        /// </summary>
        [DataMember(Name = "fx", IsRequired = true, EmitDefaultValue = true)]
        public double Fx
        {
            get{ return _Fx;}
            set
            {
                _Fx = value;
                _flagFx = true;
            }
        }
        private double _Fx;
        private bool _flagFx;

        /// <summary>
        /// Returns false as Fx should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeFx()
        {
            return _flagFx;
        }
        /// <summary>
        /// Gets or Sets Fy
        /// </summary>
        [DataMember(Name = "fy", IsRequired = true, EmitDefaultValue = true)]
        public double Fy
        {
            get{ return _Fy;}
            set
            {
                _Fy = value;
                _flagFy = true;
            }
        }
        private double _Fy;
        private bool _flagFy;

        /// <summary>
        /// Returns false as Fy should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeFy()
        {
            return _flagFy;
        }
        /// <summary>
        /// Gets or Sets Cx
        /// </summary>
        [DataMember(Name = "cx", IsRequired = true, EmitDefaultValue = true)]
        public double Cx
        {
            get{ return _Cx;}
            set
            {
                _Cx = value;
                _flagCx = true;
            }
        }
        private double _Cx;
        private bool _flagCx;

        /// <summary>
        /// Returns false as Cx should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCx()
        {
            return _flagCx;
        }
        /// <summary>
        /// Gets or Sets Cy
        /// </summary>
        [DataMember(Name = "cy", IsRequired = true, EmitDefaultValue = true)]
        public double Cy
        {
            get{ return _Cy;}
            set
            {
                _Cy = value;
                _flagCy = true;
            }
        }
        private double _Cy;
        private bool _flagCy;

        /// <summary>
        /// Returns false as Cy should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCy()
        {
            return _flagCy;
        }
        /// <summary>
        /// Gets or Sets K1
        /// </summary>
        [DataMember(Name = "k1", IsRequired = true, EmitDefaultValue = true)]
        public double K1
        {
            get{ return _K1;}
            set
            {
                _K1 = value;
                _flagK1 = true;
            }
        }
        private double _K1;
        private bool _flagK1;

        /// <summary>
        /// Returns false as K1 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeK1()
        {
            return _flagK1;
        }
        /// <summary>
        /// Gets or Sets K2
        /// </summary>
        [DataMember(Name = "k2", IsRequired = true, EmitDefaultValue = true)]
        public double K2
        {
            get{ return _K2;}
            set
            {
                _K2 = value;
                _flagK2 = true;
            }
        }
        private double _K2;
        private bool _flagK2;

        /// <summary>
        /// Returns false as K2 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeK2()
        {
            return _flagK2;
        }
        /// <summary>
        /// Gets or Sets P1
        /// </summary>
        [DataMember(Name = "p1", IsRequired = true, EmitDefaultValue = true)]
        public double P1
        {
            get{ return _P1;}
            set
            {
                _P1 = value;
                _flagP1 = true;
            }
        }
        private double _P1;
        private bool _flagP1;

        /// <summary>
        /// Returns false as P1 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP1()
        {
            return _flagP1;
        }
        /// <summary>
        /// Gets or Sets P2
        /// </summary>
        [DataMember(Name = "p2", IsRequired = true, EmitDefaultValue = true)]
        public double P2
        {
            get{ return _P2;}
            set
            {
                _P2 = value;
                _flagP2 = true;
            }
        }
        private double _P2;
        private bool _flagP2;

        /// <summary>
        /// Returns false as P2 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP2()
        {
            return _flagP2;
        }
        /// <summary>
        /// Gets or Sets K3
        /// </summary>
        [DataMember(Name = "k3", IsRequired = true, EmitDefaultValue = true)]
        public double K3
        {
            get{ return _K3;}
            set
            {
                _K3 = value;
                _flagK3 = true;
            }
        }
        private double _K3;
        private bool _flagK3;

        /// <summary>
        /// Returns false as K3 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeK3()
        {
            return _flagK3;
        }
        /// <summary>
        /// Gets or Sets K4
        /// </summary>
        [DataMember(Name = "k4", IsRequired = true, EmitDefaultValue = true)]
        public double K4
        {
            get{ return _K4;}
            set
            {
                _K4 = value;
                _flagK4 = true;
            }
        }
        private double _K4;
        private bool _flagK4;

        /// <summary>
        /// Returns false as K4 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeK4()
        {
            return _flagK4;
        }
        /// <summary>
        /// Gets or Sets K5
        /// </summary>
        [DataMember(Name = "k5", IsRequired = true, EmitDefaultValue = true)]
        public double K5
        {
            get{ return _K5;}
            set
            {
                _K5 = value;
                _flagK5 = true;
            }
        }
        private double _K5;
        private bool _flagK5;

        /// <summary>
        /// Returns false as K5 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeK5()
        {
            return _flagK5;
        }
        /// <summary>
        /// Gets or Sets K6
        /// </summary>
        [DataMember(Name = "k6", IsRequired = true, EmitDefaultValue = true)]
        public double K6
        {
            get{ return _K6;}
            set
            {
                _K6 = value;
                _flagK6 = true;
            }
        }
        private double _K6;
        private bool _flagK6;

        /// <summary>
        /// Returns false as K6 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeK6()
        {
            return _flagK6;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FullOpenCVCamera {\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Mirroring: ").Append(Mirroring).Append("\n");
            sb.Append("  Rotation: ").Append(Rotation).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Fx: ").Append(Fx).Append("\n");
            sb.Append("  Fy: ").Append(Fy).Append("\n");
            sb.Append("  Cx: ").Append(Cx).Append("\n");
            sb.Append("  Cy: ").Append(Cy).Append("\n");
            sb.Append("  K1: ").Append(K1).Append("\n");
            sb.Append("  K2: ").Append(K2).Append("\n");
            sb.Append("  P1: ").Append(P1).Append("\n");
            sb.Append("  P2: ").Append(P2).Append("\n");
            sb.Append("  K3: ").Append(K3).Append("\n");
            sb.Append("  K4: ").Append(K4).Append("\n");
            sb.Append("  K5: ").Append(K5).Append("\n");
            sb.Append("  K6: ").Append(K6).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
