/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Plerion.Client.FileParameter;
using OpenAPIDateConverter = Plerion.Client.OpenAPIDateConverter;

namespace Plerion.Model
{
    // fuck
    /// <summary>
    /// GenericParamsIntrinsics
    /// </summary>
    [DataContract(Name = "GenericParamsIntrinsics")]
    public partial class GenericParamsIntrinsics
    {
        /// <summary>
        /// Defines Mirroring
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum MirroringEnum
        {
            /// <summary>
            /// Enum None for value: None
            /// </summary>
            [EnumMember(Value = "None")]
            None = 1,

            /// <summary>
            /// Enum X for value: X
            /// </summary>
            [EnumMember(Value = "X")]
            X = 2,

            /// <summary>
            /// Enum Y for value: Y
            /// </summary>
            [EnumMember(Value = "Y")]
            Y = 3
        }


        /// <summary>
        /// Gets or Sets Mirroring
        /// </summary>

        [DataMember(Name = "mirroring", IsRequired = true, EmitDefaultValue = true)]
        public MirroringEnum Mirroring
        {
            get{ return _Mirroring;}
            set
            {
                _Mirroring = value;
                _flagMirroring = true;
            }
        }
        private MirroringEnum _Mirroring;
        private bool _flagMirroring;

        /// <summary>
        /// Returns false as Mirroring should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMirroring()
        {
            return _flagMirroring;
        }
        /// <summary>
        /// Defines Rotation
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RotationEnum
        {
            /// <summary>
            /// Enum None for value: None
            /// </summary>
            [EnumMember(Value = "None")]
            None = 1,

            /// <summary>
            /// Enum _90CW for value: 90_CW
            /// </summary>
            [EnumMember(Value = "90_CW")]
            _90CW = 2,

            /// <summary>
            /// Enum _180 for value: 180
            /// </summary>
            [EnumMember(Value = "180")]
            _180 = 3,

            /// <summary>
            /// Enum _90CCW for value: 90_CCW
            /// </summary>
            [EnumMember(Value = "90_CCW")]
            _90CCW = 4
        }


        /// <summary>
        /// Gets or Sets Rotation
        /// </summary>

        [DataMember(Name = "rotation", IsRequired = true, EmitDefaultValue = true)]
        public RotationEnum Rotation
        {
            get{ return _Rotation;}
            set
            {
                _Rotation = value;
                _flagRotation = true;
            }
        }
        private RotationEnum _Rotation;
        private bool _flagRotation;

        /// <summary>
        /// Returns false as Rotation should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRotation()
        {
            return _flagRotation;
        }
        /// <summary>
        /// Defines Model
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ModelEnum
        {
            /// <summary>
            /// Enum GENERIC for value: GENERIC
            /// </summary>
            [EnumMember(Value = "GENERIC")]
            GENERIC = 1
        }


        /// <summary>
        /// Gets or Sets Model
        /// </summary>

        [DataMember(Name = "model", IsRequired = true, EmitDefaultValue = true)]
        public ModelEnum Model
        {
            get{ return _Model;}
            set
            {
                _Model = value;
                _flagModel = true;
            }
        }
        private ModelEnum _Model;
        private bool _flagModel;

        /// <summary>
        /// Returns false as Model should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeModel()
        {
            return _flagModel;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="GenericParamsIntrinsics" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GenericParamsIntrinsics() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GenericParamsIntrinsics" /> class.
        /// </summary>
        /// <param name="width">width (required).</param>
        /// <param name="height">height (required).</param>
        /// <param name="mirroring">mirroring (required).</param>
        /// <param name="rotation">rotation (required).</param>
        /// <param name="model">model (required).</param>
        /// <param name="varParams">varParams (required).</param>
        public GenericParamsIntrinsics(int width, int height, MirroringEnum mirroring, RotationEnum rotation, ModelEnum model, List<double> varParams)
        {
            this.Width = width;
            this.Height = height;
            this.Mirroring = mirroring;
            this.Rotation = rotation;
            this.Model = model;
            // to ensure "varParams" is required (not null)
            if (varParams == null)
            {
                throw new ArgumentNullException("varParams is a required property for GenericParamsIntrinsics and cannot be null");
            }
            this.Params = varParams;
        }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "width", IsRequired = true, EmitDefaultValue = true)]
        public int Width
        {
            get{ return _Width;}
            set
            {
                _Width = value;
                _flagWidth = true;
            }
        }
        private int _Width;
        private bool _flagWidth;

        /// <summary>
        /// Returns false as Width should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeWidth()
        {
            return _flagWidth;
        }
        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", IsRequired = true, EmitDefaultValue = true)]
        public int Height
        {
            get{ return _Height;}
            set
            {
                _Height = value;
                _flagHeight = true;
            }
        }
        private int _Height;
        private bool _flagHeight;

        /// <summary>
        /// Returns false as Height should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeHeight()
        {
            return _flagHeight;
        }
        /// <summary>
        /// Gets or Sets Params
        /// </summary>
        [DataMember(Name = "params", IsRequired = true, EmitDefaultValue = true)]
        public List<double> Params
        {
            get{ return _Params;}
            set
            {
                _Params = value;
                _flagParams = true;
            }
        }
        private List<double> _Params;
        private bool _flagParams;

        /// <summary>
        /// Returns false as Params should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeParams()
        {
            return _flagParams;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GenericParamsIntrinsics {\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Mirroring: ").Append(Mirroring).Append("\n");
            sb.Append("  Rotation: ").Append(Rotation).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Params: ").Append(Params).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
