/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Plerion.Client.FileParameter;
using OpenAPIDateConverter = Plerion.Client.OpenAPIDateConverter;

namespace Plerion.Model
{
    // fuck
    /// <summary>
    /// LocalizationMetrics
    /// </summary>
    [DataContract(Name = "LocalizationMetrics")]
    public partial class LocalizationMetrics
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMetrics" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LocalizationMetrics() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMetrics" /> class.
        /// </summary>
        /// <param name="inlierRatio">inlierRatio (required).</param>
        /// <param name="reprojectionErrorMedian">reprojectionErrorMedian (required).</param>
        /// <param name="imageCoverage">imageCoverage (required).</param>
        /// <param name="depthZ90thPercentile">depthZ90thPercentile (required).</param>
        /// <param name="depthZ10thPercentile">depthZ10thPercentile (required).</param>
        public LocalizationMetrics(double inlierRatio, double reprojectionErrorMedian, double imageCoverage, double depthZ90thPercentile, double depthZ10thPercentile)
        {
            this.InlierRatio = inlierRatio;
            this.ReprojectionErrorMedian = reprojectionErrorMedian;
            this.ImageCoverage = imageCoverage;
            this.DepthZ90thPercentile = depthZ90thPercentile;
            this.DepthZ10thPercentile = depthZ10thPercentile;
        }

        /// <summary>
        /// Gets or Sets InlierRatio
        /// </summary>
        [DataMember(Name = "inlier_ratio", IsRequired = true, EmitDefaultValue = true)]
        public double InlierRatio
        {
            get{ return _InlierRatio;}
            set
            {
                _InlierRatio = value;
                _flagInlierRatio = true;
            }
        }
        private double _InlierRatio;
        private bool _flagInlierRatio;

        /// <summary>
        /// Returns false as InlierRatio should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInlierRatio()
        {
            return _flagInlierRatio;
        }
        /// <summary>
        /// Gets or Sets ReprojectionErrorMedian
        /// </summary>
        [DataMember(Name = "reprojection_error_median", IsRequired = true, EmitDefaultValue = true)]
        public double ReprojectionErrorMedian
        {
            get{ return _ReprojectionErrorMedian;}
            set
            {
                _ReprojectionErrorMedian = value;
                _flagReprojectionErrorMedian = true;
            }
        }
        private double _ReprojectionErrorMedian;
        private bool _flagReprojectionErrorMedian;

        /// <summary>
        /// Returns false as ReprojectionErrorMedian should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeReprojectionErrorMedian()
        {
            return _flagReprojectionErrorMedian;
        }
        /// <summary>
        /// Gets or Sets ImageCoverage
        /// </summary>
        [DataMember(Name = "image_coverage", IsRequired = true, EmitDefaultValue = true)]
        public double ImageCoverage
        {
            get{ return _ImageCoverage;}
            set
            {
                _ImageCoverage = value;
                _flagImageCoverage = true;
            }
        }
        private double _ImageCoverage;
        private bool _flagImageCoverage;

        /// <summary>
        /// Returns false as ImageCoverage should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeImageCoverage()
        {
            return _flagImageCoverage;
        }
        /// <summary>
        /// Gets or Sets DepthZ90thPercentile
        /// </summary>
        [DataMember(Name = "depth_z_90th_percentile", IsRequired = true, EmitDefaultValue = true)]
        public double DepthZ90thPercentile
        {
            get{ return _DepthZ90thPercentile;}
            set
            {
                _DepthZ90thPercentile = value;
                _flagDepthZ90thPercentile = true;
            }
        }
        private double _DepthZ90thPercentile;
        private bool _flagDepthZ90thPercentile;

        /// <summary>
        /// Returns false as DepthZ90thPercentile should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDepthZ90thPercentile()
        {
            return _flagDepthZ90thPercentile;
        }
        /// <summary>
        /// Gets or Sets DepthZ10thPercentile
        /// </summary>
        [DataMember(Name = "depth_z_10th_percentile", IsRequired = true, EmitDefaultValue = true)]
        public double DepthZ10thPercentile
        {
            get{ return _DepthZ10thPercentile;}
            set
            {
                _DepthZ10thPercentile = value;
                _flagDepthZ10thPercentile = true;
            }
        }
        private double _DepthZ10thPercentile;
        private bool _flagDepthZ10thPercentile;

        /// <summary>
        /// Returns false as DepthZ10thPercentile should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDepthZ10thPercentile()
        {
            return _flagDepthZ10thPercentile;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LocalizationMetrics {\n");
            sb.Append("  InlierRatio: ").Append(InlierRatio).Append("\n");
            sb.Append("  ReprojectionErrorMedian: ").Append(ReprojectionErrorMedian).Append("\n");
            sb.Append("  ImageCoverage: ").Append(ImageCoverage).Append("\n");
            sb.Append("  DepthZ90thPercentile: ").Append(DepthZ90thPercentile).Append("\n");
            sb.Append("  DepthZ10thPercentile: ").Append(DepthZ10thPercentile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
