/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Plerion.Client.FileParameter;
using OpenAPIDateConverter = Plerion.Client.OpenAPIDateConverter;

namespace Plerion.Model
{
    // fuck
    /// <summary>
    /// PointCloudPoint
    /// </summary>
    [DataContract(Name = "PointCloudPoint")]
    public partial class PointCloudPoint
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PointCloudPoint" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PointCloudPoint() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PointCloudPoint" /> class.
        /// </summary>
        /// <param name="position">position (required).</param>
        /// <param name="color">color (required).</param>
        public PointCloudPoint(Vector3 position, Color color)
        {
            // to ensure "position" is required (not null)
            if (position == null)
            {
                throw new ArgumentNullException("position is a required property for PointCloudPoint and cannot be null");
            }
            this.Position = position;
            // to ensure "color" is required (not null)
            if (color == null)
            {
                throw new ArgumentNullException("color is a required property for PointCloudPoint and cannot be null");
            }
            this.Color = color;
        }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", IsRequired = true, EmitDefaultValue = true)]
        public Vector3 Position
        {
            get{ return _Position;}
            set
            {
                _Position = value;
                _flagPosition = true;
            }
        }
        private Vector3 _Position;
        private bool _flagPosition;

        /// <summary>
        /// Returns false as Position should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePosition()
        {
            return _flagPosition;
        }
        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [DataMember(Name = "color", IsRequired = true, EmitDefaultValue = true)]
        public Color Color
        {
            get{ return _Color;}
            set
            {
                _Color = value;
                _flagColor = true;
            }
        }
        private Color _Color;
        private bool _flagColor;

        /// <summary>
        /// Returns false as Color should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeColor()
        {
            return _flagColor;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PointCloudPoint {\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
