/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = Plerion.Client.FileParameter;
using OpenAPIDateConverter = Plerion.Client.OpenAPIDateConverter;

namespace Plerion.Model
{
    // fuck
    /// <summary>
    /// ReconstructionManifest
    /// </summary>
    [DataContract(Name = "ReconstructionManifest")]
    public partial class ReconstructionManifest
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Queued for value: queued
            /// </summary>
            [EnumMember(Value = "queued")]
            Queued = 1,

            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 2,

            /// <summary>
            /// Enum Downloading for value: downloading
            /// </summary>
            [EnumMember(Value = "downloading")]
            Downloading = 3,

            /// <summary>
            /// Enum ExtractingFeatures for value: extracting_features
            /// </summary>
            [EnumMember(Value = "extracting_features")]
            ExtractingFeatures = 4,

            /// <summary>
            /// Enum MatchingFeatures for value: matching_features
            /// </summary>
            [EnumMember(Value = "matching_features")]
            MatchingFeatures = 5,

            /// <summary>
            /// Enum Reconstructing for value: reconstructing
            /// </summary>
            [EnumMember(Value = "reconstructing")]
            Reconstructing = 6,

            /// <summary>
            /// Enum TrainingOpqMatrix for value: training_opq_matrix
            /// </summary>
            [EnumMember(Value = "training_opq_matrix")]
            TrainingOpqMatrix = 7,

            /// <summary>
            /// Enum TrainingProductQuantizer for value: training_product_quantizer
            /// </summary>
            [EnumMember(Value = "training_product_quantizer")]
            TrainingProductQuantizer = 8,

            /// <summary>
            /// Enum Uploading for value: uploading
            /// </summary>
            [EnumMember(Value = "uploading")]
            Uploading = 9,

            /// <summary>
            /// Enum Succeeded for value: succeeded
            /// </summary>
            [EnumMember(Value = "succeeded")]
            Succeeded = 10,

            /// <summary>
            /// Enum Failed for value: failed
            /// </summary>
            [EnumMember(Value = "failed")]
            Failed = 11
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>

        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status
        {
            get{ return _Status;}
            set
            {
                _Status = value;
                _flagStatus = true;
            }
        }
        private StatusEnum _Status;
        private bool _flagStatus;

        /// <summary>
        /// Returns false as Status should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStatus()
        {
            return _flagStatus;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReconstructionManifest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReconstructionManifest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReconstructionManifest" /> class.
        /// </summary>
        /// <param name="captureId">captureId (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="error">error.</param>
        /// <param name="options">options (required).</param>
        /// <param name="metrics">metrics (required).</param>
        public ReconstructionManifest(string captureId, StatusEnum status, ReconstructionOptions options, ReconstructionMetrics metrics)
        {
            // to ensure "captureId" is required (not null)
            if (captureId == null)
            {
                throw new ArgumentNullException("captureId is a required property for ReconstructionManifest and cannot be null");
            }
            this.CaptureId = captureId;
            this.Status = status;
            // to ensure "options" is required (not null)
            if (options == null)
            {
                throw new ArgumentNullException("options is a required property for ReconstructionManifest and cannot be null");
            }
            this.Options = options;
            // to ensure "metrics" is required (not null)
            if (metrics == null)
            {
                throw new ArgumentNullException("metrics is a required property for ReconstructionManifest and cannot be null");
            }
            this.Metrics = metrics;
        }

        /// <summary>
        /// Gets or Sets CaptureId
        /// </summary>
        [DataMember(Name = "capture_id", IsRequired = true, EmitDefaultValue = true)]
        public string CaptureId
        {
            get{ return _CaptureId;}
            set
            {
                _CaptureId = value;
                _flagCaptureId = true;
            }
        }
        private string _CaptureId;
        private bool _flagCaptureId;

        /// <summary>
        /// Returns false as CaptureId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCaptureId()
        {
            return _flagCaptureId;
        }
        /// <summary>
        /// Gets or Sets Options
        /// </summary>
        [DataMember(Name = "options", IsRequired = true, EmitDefaultValue = true)]
        public ReconstructionOptions Options
        {
            get{ return _Options;}
            set
            {
                _Options = value;
                _flagOptions = true;
            }
        }
        private ReconstructionOptions _Options;
        private bool _flagOptions;

        /// <summary>
        /// Returns false as Options should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeOptions()
        {
            return _flagOptions;
        }
        /// <summary>
        /// Gets or Sets Metrics
        /// </summary>
        [DataMember(Name = "metrics", IsRequired = true, EmitDefaultValue = true)]
        public ReconstructionMetrics Metrics
        {
            get{ return _Metrics;}
            set
            {
                _Metrics = value;
                _flagMetrics = true;
            }
        }
        private ReconstructionMetrics _Metrics;
        private bool _flagMetrics;

        /// <summary>
        /// Returns false as Metrics should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMetrics()
        {
            return _flagMetrics;
        }
        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = true)]
        public string Error
        {
            get{ return _Error;}
            set
            {
                _Error = value;
                _flagError = true;
            }
        }
        private string _Error;
        private bool _flagError;

        /// <summary>
        /// Returns false as Error should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeError()
        {
            return _flagError;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReconstructionManifest {\n");
            sb.Append("  CaptureId: ").Append(CaptureId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  Metrics: ").Append(Metrics).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
