environment:
  - plerion/core
  - plerion/dev

config:
  aws:region: us-east-1
  plerion_infra:github-branch: main
  plerion_infra:deploy-cloudbeaver: false
  plerion_infra:deploy-database-manager: false
  plerion_infra:deploy-tailscale-beacon: true
  plerion_infra:deploy-auth-gateway: true