/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using PlerionClient.Client;
using PlerionClient.Model;

namespace PlerionClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Capture
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateCapture"></param>
        /// <returns>CaptureModel</returns>
        CaptureModel CreateCapture(BodyCreateCapture bodyCreateCapture);

        /// <summary>
        /// Create Capture
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateCapture"></param>
        /// <returns>ApiResponse of CaptureModel</returns>
        ApiResponse<CaptureModel> CreateCaptureWithHttpInfo(BodyCreateCapture bodyCreateCapture);
        /// <summary>
        /// Create Node
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateNode"></param>
        /// <returns>NodeModel</returns>
        NodeModel CreateNode(BodyCreateNode bodyCreateNode);

        /// <summary>
        /// Create Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateNode"></param>
        /// <returns>ApiResponse of NodeModel</returns>
        ApiResponse<NodeModel> CreateNodeWithHttpInfo(BodyCreateNode bodyCreateNode);
        /// <summary>
        /// Create Reconstruction
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captureId"></param>
        /// <returns>Object</returns>
        Object CreateReconstruction(Guid captureId);

        /// <summary>
        /// Create Reconstruction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captureId"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> CreateReconstructionWithHttpInfo(Guid captureId);
        /// <summary>
        /// Download Capture Tar
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>FileParameter</returns>
        FileParameter DownloadCaptureTar(Guid id);

        /// <summary>
        /// Download Capture Tar
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of FileParameter</returns>
        ApiResponse<FileParameter> DownloadCaptureTarWithHttpInfo(Guid id);
        /// <summary>
        /// Get Capture
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>CaptureModel</returns>
        CaptureModel GetCapture(Guid id);

        /// <summary>
        /// Get Capture
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of CaptureModel</returns>
        ApiResponse<CaptureModel> GetCaptureWithHttpInfo(Guid id);
        /// <summary>
        /// Get Captures
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>List&lt;CaptureModel&gt;</returns>
        List<CaptureModel> GetCaptures(List<Guid> ids = default);

        /// <summary>
        /// Get Captures
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>ApiResponse of List&lt;CaptureModel&gt;</returns>
        ApiResponse<List<CaptureModel>> GetCapturesWithHttpInfo(List<Guid> ids = default);
        /// <summary>
        /// Get Node
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>NodeModel</returns>
        NodeModel GetNode(Guid id);

        /// <summary>
        /// Get Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of NodeModel</returns>
        ApiResponse<NodeModel> GetNodeWithHttpInfo(Guid id);
        /// <summary>
        /// Get Nodes
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>List&lt;NodeModel&gt;</returns>
        List<NodeModel> GetNodes(List<Guid> ids = default);

        /// <summary>
        /// Get Nodes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>ApiResponse of List&lt;NodeModel&gt;</returns>
        ApiResponse<List<NodeModel>> GetNodesWithHttpInfo(List<Guid> ids = default);
        /// <summary>
        /// Upload Capture Tar
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body"></param>
        /// <returns></returns>
        void UploadCaptureTar(Guid id, FileParameter body);

        /// <summary>
        /// Upload Capture Tar
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UploadCaptureTarWithHttpInfo(Guid id, FileParameter body);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Capture
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateCapture"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CaptureModel</returns>
        System.Threading.Tasks.Task<CaptureModel> CreateCaptureAsync(BodyCreateCapture bodyCreateCapture, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create Capture
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateCapture"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CaptureModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<CaptureModel>> CreateCaptureWithHttpInfoAsync(BodyCreateCapture bodyCreateCapture, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateNode"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of NodeModel</returns>
        System.Threading.Tasks.Task<NodeModel> CreateNodeAsync(BodyCreateNode bodyCreateNode, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateNode"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (NodeModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<NodeModel>> CreateNodeWithHttpInfoAsync(BodyCreateNode bodyCreateNode, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Create Reconstruction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captureId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> CreateReconstructionAsync(Guid captureId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create Reconstruction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captureId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateReconstructionWithHttpInfoAsync(Guid captureId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Download Capture Tar
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FileParameter</returns>
        System.Threading.Tasks.Task<FileParameter> DownloadCaptureTarAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Download Capture Tar
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FileParameter)</returns>
        System.Threading.Tasks.Task<ApiResponse<FileParameter>> DownloadCaptureTarWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Capture
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CaptureModel</returns>
        System.Threading.Tasks.Task<CaptureModel> GetCaptureAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Capture
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CaptureModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<CaptureModel>> GetCaptureWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Captures
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CaptureModel&gt;</returns>
        System.Threading.Tasks.Task<List<CaptureModel>> GetCapturesAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Captures
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CaptureModel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<CaptureModel>>> GetCapturesWithHttpInfoAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of NodeModel</returns>
        System.Threading.Tasks.Task<NodeModel> GetNodeAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (NodeModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<NodeModel>> GetNodeWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Nodes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NodeModel&gt;</returns>
        System.Threading.Tasks.Task<List<NodeModel>> GetNodesAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Nodes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NodeModel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<NodeModel>>> GetNodesWithHttpInfoAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Upload Capture Tar
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UploadCaptureTarAsync(Guid id, FileParameter body, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Upload Capture Tar
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UploadCaptureTarWithHttpInfoAsync(Guid id, FileParameter body, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IDefaultApiSync, IDefaultApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDisposable, IDefaultApi
    {
        private PlerionClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DefaultApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DefaultApi(string basePath)
        {
            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                new PlerionClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DefaultApi(PlerionClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DefaultApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DefaultApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                new PlerionClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DefaultApi(HttpClient client, PlerionClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DefaultApi(PlerionClient.Client.ISynchronousClient client, PlerionClient.Client.IAsynchronousClient asyncClient, PlerionClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public PlerionClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public PlerionClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public PlerionClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public PlerionClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public PlerionClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Capture 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateCapture"></param>
        /// <returns>CaptureModel</returns>
        public CaptureModel CreateCapture(BodyCreateCapture bodyCreateCapture)
        {
            PlerionClient.Client.ApiResponse<CaptureModel> localVarResponse = CreateCaptureWithHttpInfo(bodyCreateCapture);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Capture 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateCapture"></param>
        /// <returns>ApiResponse of CaptureModel</returns>
        public PlerionClient.Client.ApiResponse<CaptureModel> CreateCaptureWithHttpInfo(BodyCreateCapture bodyCreateCapture)
        {
            // verify the required parameter 'bodyCreateCapture' is set
            if (bodyCreateCapture == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'bodyCreateCapture' when calling DefaultApi->CreateCapture");

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bodyCreateCapture;


            // make the HTTP request
            var localVarResponse = this.Client.Post<CaptureModel>("/captures", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCapture", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Capture 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateCapture"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CaptureModel</returns>
        public async System.Threading.Tasks.Task<CaptureModel> CreateCaptureAsync(BodyCreateCapture bodyCreateCapture, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<CaptureModel> localVarResponse = await CreateCaptureWithHttpInfoAsync(bodyCreateCapture, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Capture 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateCapture"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CaptureModel)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<CaptureModel>> CreateCaptureWithHttpInfoAsync(BodyCreateCapture bodyCreateCapture, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'bodyCreateCapture' is set
            if (bodyCreateCapture == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'bodyCreateCapture' when calling DefaultApi->CreateCapture");


            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bodyCreateCapture;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CaptureModel>("/captures", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCapture", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateNode"></param>
        /// <returns>NodeModel</returns>
        public NodeModel CreateNode(BodyCreateNode bodyCreateNode)
        {
            PlerionClient.Client.ApiResponse<NodeModel> localVarResponse = CreateNodeWithHttpInfo(bodyCreateNode);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateNode"></param>
        /// <returns>ApiResponse of NodeModel</returns>
        public PlerionClient.Client.ApiResponse<NodeModel> CreateNodeWithHttpInfo(BodyCreateNode bodyCreateNode)
        {
            // verify the required parameter 'bodyCreateNode' is set
            if (bodyCreateNode == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'bodyCreateNode' when calling DefaultApi->CreateNode");

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bodyCreateNode;


            // make the HTTP request
            var localVarResponse = this.Client.Post<NodeModel>("/nodes", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateNode"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of NodeModel</returns>
        public async System.Threading.Tasks.Task<NodeModel> CreateNodeAsync(BodyCreateNode bodyCreateNode, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<NodeModel> localVarResponse = await CreateNodeWithHttpInfoAsync(bodyCreateNode, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bodyCreateNode"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (NodeModel)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<NodeModel>> CreateNodeWithHttpInfoAsync(BodyCreateNode bodyCreateNode, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'bodyCreateNode' is set
            if (bodyCreateNode == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'bodyCreateNode' when calling DefaultApi->CreateNode");


            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = bodyCreateNode;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<NodeModel>("/nodes", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Reconstruction 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captureId"></param>
        /// <returns>Object</returns>
        public Object CreateReconstruction(Guid captureId)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = CreateReconstructionWithHttpInfo(captureId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Reconstruction 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captureId"></param>
        /// <returns>ApiResponse of Object</returns>
        public PlerionClient.Client.ApiResponse<Object> CreateReconstructionWithHttpInfo(Guid captureId)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("", "capture_id", captureId));


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/reconstructions", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateReconstruction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Reconstruction 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captureId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> CreateReconstructionAsync(Guid captureId, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = await CreateReconstructionWithHttpInfoAsync(captureId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Reconstruction 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="captureId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<Object>> CreateReconstructionWithHttpInfoAsync(Guid captureId, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("", "capture_id", captureId));


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/reconstructions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateReconstruction", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Download Capture Tar 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>FileParameter</returns>
        public FileParameter DownloadCaptureTar(Guid id)
        {
            PlerionClient.Client.ApiResponse<FileParameter> localVarResponse = DownloadCaptureTarWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Download Capture Tar 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of FileParameter</returns>
        public PlerionClient.Client.ApiResponse<FileParameter> DownloadCaptureTarWithHttpInfo(Guid id)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/x-tar"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<FileParameter>("/captures/{id}/tar", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DownloadCaptureTar", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Download Capture Tar 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FileParameter</returns>
        public async System.Threading.Tasks.Task<FileParameter> DownloadCaptureTarAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<FileParameter> localVarResponse = await DownloadCaptureTarWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Download Capture Tar 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FileParameter)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<FileParameter>> DownloadCaptureTarWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "application/x-tar"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<FileParameter>("/captures/{id}/tar", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DownloadCaptureTar", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Capture 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>CaptureModel</returns>
        public CaptureModel GetCapture(Guid id)
        {
            PlerionClient.Client.ApiResponse<CaptureModel> localVarResponse = GetCaptureWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Capture 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of CaptureModel</returns>
        public PlerionClient.Client.ApiResponse<CaptureModel> GetCaptureWithHttpInfo(Guid id)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<CaptureModel>("/captures/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCapture", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Capture 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CaptureModel</returns>
        public async System.Threading.Tasks.Task<CaptureModel> GetCaptureAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<CaptureModel> localVarResponse = await GetCaptureWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Capture 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CaptureModel)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<CaptureModel>> GetCaptureWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<CaptureModel>("/captures/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCapture", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Captures 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>List&lt;CaptureModel&gt;</returns>
        public List<CaptureModel> GetCaptures(List<Guid> ids = default)
        {
            PlerionClient.Client.ApiResponse<List<CaptureModel>> localVarResponse = GetCapturesWithHttpInfo(ids);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Captures 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>ApiResponse of List&lt;CaptureModel&gt;</returns>
        public PlerionClient.Client.ApiResponse<List<CaptureModel>> GetCapturesWithHttpInfo(List<Guid> ids = default)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("multi", "ids", ids));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<CaptureModel>>("/captures", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCaptures", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Captures 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;CaptureModel&gt;</returns>
        public async System.Threading.Tasks.Task<List<CaptureModel>> GetCapturesAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<List<CaptureModel>> localVarResponse = await GetCapturesWithHttpInfoAsync(ids, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Captures 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;CaptureModel&gt;)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<List<CaptureModel>>> GetCapturesWithHttpInfoAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("multi", "ids", ids));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<CaptureModel>>("/captures", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCaptures", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>NodeModel</returns>
        public NodeModel GetNode(Guid id)
        {
            PlerionClient.Client.ApiResponse<NodeModel> localVarResponse = GetNodeWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of NodeModel</returns>
        public PlerionClient.Client.ApiResponse<NodeModel> GetNodeWithHttpInfo(Guid id)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<NodeModel>("/nodes/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of NodeModel</returns>
        public async System.Threading.Tasks.Task<NodeModel> GetNodeAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<NodeModel> localVarResponse = await GetNodeWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (NodeModel)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<NodeModel>> GetNodeWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<NodeModel>("/nodes/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Nodes 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>List&lt;NodeModel&gt;</returns>
        public List<NodeModel> GetNodes(List<Guid> ids = default)
        {
            PlerionClient.Client.ApiResponse<List<NodeModel>> localVarResponse = GetNodesWithHttpInfo(ids);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Nodes 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>ApiResponse of List&lt;NodeModel&gt;</returns>
        public PlerionClient.Client.ApiResponse<List<NodeModel>> GetNodesWithHttpInfo(List<Guid> ids = default)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("multi", "ids", ids));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<NodeModel>>("/nodes", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNodes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Nodes 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NodeModel&gt;</returns>
        public async System.Threading.Tasks.Task<List<NodeModel>> GetNodesAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<List<NodeModel>> localVarResponse = await GetNodesWithHttpInfoAsync(ids, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Nodes 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NodeModel&gt;)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<List<NodeModel>>> GetNodesWithHttpInfoAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("multi", "ids", ids));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<NodeModel>>("/nodes", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNodes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Upload Capture Tar 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body"></param>
        /// <returns></returns>
        public void UploadCaptureTar(Guid id, FileParameter body)
        {
            UploadCaptureTarWithHttpInfo(id, body);
        }

        /// <summary>
        /// Upload Capture Tar 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public PlerionClient.Client.ApiResponse<Object> UploadCaptureTarWithHttpInfo(Guid id, FileParameter body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'body' when calling DefaultApi->UploadCaptureTar");

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/x-tar"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = body;


            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/captures/{id}/tar", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UploadCaptureTar", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Upload Capture Tar 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UploadCaptureTarAsync(Guid id, FileParameter body, System.Threading.CancellationToken cancellationToken = default)
        {
            await UploadCaptureTarWithHttpInfoAsync(id, body, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Upload Capture Tar 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="body"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<Object>> UploadCaptureTarWithHttpInfoAsync(Guid id, FileParameter body, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'body' when calling DefaultApi->UploadCaptureTar");


            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/x-tar"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = body;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/captures/{id}/tar", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UploadCaptureTar", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
