/*
 * Plerion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using PlerionClient.Client;
using PlerionClient.Model;

namespace PlerionClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILocalizationMapsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Localizationmap
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <returns>Object</returns>
        Object CreateLocalizationMap(LocalizationMapModel localizationMapModel);

        /// <summary>
        /// Create Localizationmap
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> CreateLocalizationMapWithHttpInfo(LocalizationMapModel localizationMapModel);
        /// <summary>
        /// Delete Localizationmaps
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>List&lt;Guid&gt;</returns>
        List<Guid> DeleteLocalizationMaps(List<Guid> requestBody);

        /// <summary>
        /// Delete Localizationmaps
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of List&lt;Guid&gt;</returns>
        ApiResponse<List<Guid>> DeleteLocalizationMapsWithHttpInfo(List<Guid> requestBody);
        /// <summary>
        /// Get Localizationmaps
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>List&lt;LocalizationMapModel&gt;</returns>
        List<LocalizationMapModel> GetLocalizationMaps(List<Guid> ids = default);

        /// <summary>
        /// Get Localizationmaps
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>ApiResponse of List&lt;LocalizationMapModel&gt;</returns>
        ApiResponse<List<LocalizationMapModel>> GetLocalizationMapsWithHttpInfo(List<Guid> ids = default);
        /// <summary>
        /// Update Localizationmap
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="localizationMapModel"></param>
        /// <returns>Object</returns>
        Object UpdateLocalizationMap(Guid id, LocalizationMapModel localizationMapModel);

        /// <summary>
        /// Update Localizationmap
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="localizationMapModel"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> UpdateLocalizationMapWithHttpInfo(Guid id, LocalizationMapModel localizationMapModel);
        /// <summary>
        /// Upsert Localizationmaps
        /// </summary>
        /// <remarks>
        /// Bulk upsert localizationMaps. - If a localizationMap has an id and exists → update it. - If a localizationMap has an id but doesn&#39;t exist → insert it. - If a localizationMap has no id → generate a new UUID and insert it.
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <returns>Object</returns>
        Object UpsertLocalizationMaps(List<LocalizationMapModel> localizationMapModel);

        /// <summary>
        /// Upsert Localizationmaps
        /// </summary>
        /// <remarks>
        /// Bulk upsert localizationMaps. - If a localizationMap has an id and exists → update it. - If a localizationMap has an id but doesn&#39;t exist → insert it. - If a localizationMap has no id → generate a new UUID and insert it.
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> UpsertLocalizationMapsWithHttpInfo(List<LocalizationMapModel> localizationMapModel);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILocalizationMapsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Localizationmap
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> CreateLocalizationMapAsync(LocalizationMapModel localizationMapModel, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create Localizationmap
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateLocalizationMapWithHttpInfoAsync(LocalizationMapModel localizationMapModel, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete Localizationmaps
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Guid&gt;</returns>
        System.Threading.Tasks.Task<List<Guid>> DeleteLocalizationMapsAsync(List<Guid> requestBody, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete Localizationmaps
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Guid&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Guid>>> DeleteLocalizationMapsWithHttpInfoAsync(List<Guid> requestBody, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Localizationmaps
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;LocalizationMapModel&gt;</returns>
        System.Threading.Tasks.Task<List<LocalizationMapModel>> GetLocalizationMapsAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Localizationmaps
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;LocalizationMapModel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<LocalizationMapModel>>> GetLocalizationMapsWithHttpInfoAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Update Localizationmap
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> UpdateLocalizationMapAsync(Guid id, LocalizationMapModel localizationMapModel, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Update Localizationmap
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UpdateLocalizationMapWithHttpInfoAsync(Guid id, LocalizationMapModel localizationMapModel, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Upsert Localizationmaps
        /// </summary>
        /// <remarks>
        /// Bulk upsert localizationMaps. - If a localizationMap has an id and exists → update it. - If a localizationMap has an id but doesn&#39;t exist → insert it. - If a localizationMap has no id → generate a new UUID and insert it.
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> UpsertLocalizationMapsAsync(List<LocalizationMapModel> localizationMapModel, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Upsert Localizationmaps
        /// </summary>
        /// <remarks>
        /// Bulk upsert localizationMaps. - If a localizationMap has an id and exists → update it. - If a localizationMap has an id but doesn&#39;t exist → insert it. - If a localizationMap has no id → generate a new UUID and insert it.
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UpsertLocalizationMapsWithHttpInfoAsync(List<LocalizationMapModel> localizationMapModel, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILocalizationMapsApi : ILocalizationMapsApiSync, ILocalizationMapsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LocalizationMapsApi : IDisposable, ILocalizationMapsApi
    {
        private PlerionClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMapsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public LocalizationMapsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMapsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public LocalizationMapsApi(string basePath)
        {
            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                new PlerionClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMapsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public LocalizationMapsApi(PlerionClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMapsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public LocalizationMapsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMapsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public LocalizationMapsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                new PlerionClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMapsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public LocalizationMapsApi(HttpClient client, PlerionClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationMapsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public LocalizationMapsApi(PlerionClient.Client.ISynchronousClient client, PlerionClient.Client.IAsynchronousClient asyncClient, PlerionClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public PlerionClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public PlerionClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public PlerionClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public PlerionClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public PlerionClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Localizationmap 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <returns>Object</returns>
        public Object CreateLocalizationMap(LocalizationMapModel localizationMapModel)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = CreateLocalizationMapWithHttpInfo(localizationMapModel);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Localizationmap 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <returns>ApiResponse of Object</returns>
        public PlerionClient.Client.ApiResponse<Object> CreateLocalizationMapWithHttpInfo(LocalizationMapModel localizationMapModel)
        {
            // verify the required parameter 'localizationMapModel' is set
            if (localizationMapModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'localizationMapModel' when calling LocalizationMapsApi->CreateLocalizationMap");

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = localizationMapModel;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/localizationMaps", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateLocalizationMap", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Localizationmap 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> CreateLocalizationMapAsync(LocalizationMapModel localizationMapModel, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = await CreateLocalizationMapWithHttpInfoAsync(localizationMapModel, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Localizationmap 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<Object>> CreateLocalizationMapWithHttpInfoAsync(LocalizationMapModel localizationMapModel, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'localizationMapModel' is set
            if (localizationMapModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'localizationMapModel' when calling LocalizationMapsApi->CreateLocalizationMap");


            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = localizationMapModel;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/localizationMaps", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateLocalizationMap", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Localizationmaps 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>List&lt;Guid&gt;</returns>
        public List<Guid> DeleteLocalizationMaps(List<Guid> requestBody)
        {
            PlerionClient.Client.ApiResponse<List<Guid>> localVarResponse = DeleteLocalizationMapsWithHttpInfo(requestBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Localizationmaps 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <returns>ApiResponse of List&lt;Guid&gt;</returns>
        public PlerionClient.Client.ApiResponse<List<Guid>> DeleteLocalizationMapsWithHttpInfo(List<Guid> requestBody)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'requestBody' when calling LocalizationMapsApi->DeleteLocalizationMaps");

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;


            // make the HTTP request
            var localVarResponse = this.Client.Delete<List<Guid>>("/localizationMaps/", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteLocalizationMaps", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Localizationmaps 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Guid&gt;</returns>
        public async System.Threading.Tasks.Task<List<Guid>> DeleteLocalizationMapsAsync(List<Guid> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<List<Guid>> localVarResponse = await DeleteLocalizationMapsWithHttpInfoAsync(requestBody, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Localizationmaps 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Guid&gt;)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<List<Guid>>> DeleteLocalizationMapsWithHttpInfoAsync(List<Guid> requestBody, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'requestBody' is set
            if (requestBody == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'requestBody' when calling LocalizationMapsApi->DeleteLocalizationMaps");


            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = requestBody;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<List<Guid>>("/localizationMaps/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteLocalizationMaps", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Localizationmaps 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>List&lt;LocalizationMapModel&gt;</returns>
        public List<LocalizationMapModel> GetLocalizationMaps(List<Guid> ids = default)
        {
            PlerionClient.Client.ApiResponse<List<LocalizationMapModel>> localVarResponse = GetLocalizationMapsWithHttpInfo(ids);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Localizationmaps 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>ApiResponse of List&lt;LocalizationMapModel&gt;</returns>
        public PlerionClient.Client.ApiResponse<List<LocalizationMapModel>> GetLocalizationMapsWithHttpInfo(List<Guid> ids = default)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("multi", "ids", ids));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<LocalizationMapModel>>("/localizationMaps", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLocalizationMaps", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Localizationmaps 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;LocalizationMapModel&gt;</returns>
        public async System.Threading.Tasks.Task<List<LocalizationMapModel>> GetLocalizationMapsAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<List<LocalizationMapModel>> localVarResponse = await GetLocalizationMapsWithHttpInfoAsync(ids, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Localizationmaps 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;LocalizationMapModel&gt;)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<List<LocalizationMapModel>>> GetLocalizationMapsWithHttpInfoAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("multi", "ids", ids));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<LocalizationMapModel>>("/localizationMaps", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLocalizationMaps", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Localizationmap 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="localizationMapModel"></param>
        /// <returns>Object</returns>
        public Object UpdateLocalizationMap(Guid id, LocalizationMapModel localizationMapModel)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = UpdateLocalizationMapWithHttpInfo(id, localizationMapModel);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Localizationmap 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="localizationMapModel"></param>
        /// <returns>ApiResponse of Object</returns>
        public PlerionClient.Client.ApiResponse<Object> UpdateLocalizationMapWithHttpInfo(Guid id, LocalizationMapModel localizationMapModel)
        {
            // verify the required parameter 'localizationMapModel' is set
            if (localizationMapModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'localizationMapModel' when calling LocalizationMapsApi->UpdateLocalizationMap");

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = localizationMapModel;


            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/localizationMaps/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateLocalizationMap", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Localizationmap 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> UpdateLocalizationMapAsync(Guid id, LocalizationMapModel localizationMapModel, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = await UpdateLocalizationMapWithHttpInfoAsync(id, localizationMapModel, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Localizationmap 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<Object>> UpdateLocalizationMapWithHttpInfoAsync(Guid id, LocalizationMapModel localizationMapModel, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'localizationMapModel' is set
            if (localizationMapModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'localizationMapModel' when calling LocalizationMapsApi->UpdateLocalizationMap");


            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = localizationMapModel;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/localizationMaps/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateLocalizationMap", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Upsert Localizationmaps Bulk upsert localizationMaps. - If a localizationMap has an id and exists → update it. - If a localizationMap has an id but doesn&#39;t exist → insert it. - If a localizationMap has no id → generate a new UUID and insert it.
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <returns>Object</returns>
        public Object UpsertLocalizationMaps(List<LocalizationMapModel> localizationMapModel)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = UpsertLocalizationMapsWithHttpInfo(localizationMapModel);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Upsert Localizationmaps Bulk upsert localizationMaps. - If a localizationMap has an id and exists → update it. - If a localizationMap has an id but doesn&#39;t exist → insert it. - If a localizationMap has no id → generate a new UUID and insert it.
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <returns>ApiResponse of Object</returns>
        public PlerionClient.Client.ApiResponse<Object> UpsertLocalizationMapsWithHttpInfo(List<LocalizationMapModel> localizationMapModel)
        {
            // verify the required parameter 'localizationMapModel' is set
            if (localizationMapModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'localizationMapModel' when calling LocalizationMapsApi->UpsertLocalizationMaps");

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = localizationMapModel;


            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/localizationMaps/upsert", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpsertLocalizationMaps", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Upsert Localizationmaps Bulk upsert localizationMaps. - If a localizationMap has an id and exists → update it. - If a localizationMap has an id but doesn&#39;t exist → insert it. - If a localizationMap has no id → generate a new UUID and insert it.
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> UpsertLocalizationMapsAsync(List<LocalizationMapModel> localizationMapModel, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = await UpsertLocalizationMapsWithHttpInfoAsync(localizationMapModel, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Upsert Localizationmaps Bulk upsert localizationMaps. - If a localizationMap has an id and exists → update it. - If a localizationMap has an id but doesn&#39;t exist → insert it. - If a localizationMap has no id → generate a new UUID and insert it.
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="localizationMapModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<Object>> UpsertLocalizationMapsWithHttpInfoAsync(List<LocalizationMapModel> localizationMapModel, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'localizationMapModel' is set
            if (localizationMapModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'localizationMapModel' when calling LocalizationMapsApi->UpsertLocalizationMaps");


            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = localizationMapModel;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/localizationMaps/upsert", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpsertLocalizationMaps", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
