/*
 * Plerion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using PlerionClient.Client;
using PlerionClient.Model;

namespace PlerionClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INodesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Node
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="nodeModel"></param>
        /// <returns>Object</returns>
        Object CreateNode(NodeModel nodeModel);

        /// <summary>
        /// Create Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="nodeModel"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> CreateNodeWithHttpInfo(NodeModel nodeModel);
        /// <summary>
        /// Delete Node
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Object</returns>
        Object DeleteNode(Guid id);

        /// <summary>
        /// Delete Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> DeleteNodeWithHttpInfo(Guid id);
        /// <summary>
        /// Get Node
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Object</returns>
        Object GetNode(Guid id);

        /// <summary>
        /// Get Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> GetNodeWithHttpInfo(Guid id);
        /// <summary>
        /// Get Nodes
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>List&lt;NodeModel&gt;</returns>
        List<NodeModel> GetNodes(List<Guid> ids = default);

        /// <summary>
        /// Get Nodes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>ApiResponse of List&lt;NodeModel&gt;</returns>
        ApiResponse<List<NodeModel>> GetNodesWithHttpInfo(List<Guid> ids = default);
        /// <summary>
        /// Update Node
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="nodeModel"></param>
        /// <returns>Object</returns>
        Object UpdateNode(Guid id, NodeModel nodeModel);

        /// <summary>
        /// Update Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="nodeModel"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<Object> UpdateNodeWithHttpInfo(Guid id, NodeModel nodeModel);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INodesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="nodeModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> CreateNodeAsync(NodeModel nodeModel, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="nodeModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateNodeWithHttpInfoAsync(NodeModel nodeModel, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> DeleteNodeAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteNodeWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> GetNodeAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> GetNodeWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get Nodes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NodeModel&gt;</returns>
        System.Threading.Tasks.Task<List<NodeModel>> GetNodesAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Nodes
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NodeModel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<NodeModel>>> GetNodesWithHttpInfoAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Update Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="nodeModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<Object> UpdateNodeAsync(Guid id, NodeModel nodeModel, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Update Node
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="nodeModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UpdateNodeWithHttpInfoAsync(Guid id, NodeModel nodeModel, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INodesApi : INodesApiSync, INodesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NodesApi : IDisposable, INodesApi
    {
        private PlerionClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NodesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public NodesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NodesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public NodesApi(string basePath)
        {
            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                new PlerionClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NodesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public NodesApi(PlerionClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NodesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public NodesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NodesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public NodesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                new PlerionClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NodesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public NodesApi(HttpClient client, PlerionClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = PlerionClient.Client.Configuration.MergeConfigurations(
                PlerionClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new PlerionClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NodesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public NodesApi(PlerionClient.Client.ISynchronousClient client, PlerionClient.Client.IAsynchronousClient asyncClient, PlerionClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = PlerionClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public PlerionClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public PlerionClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public PlerionClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public PlerionClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public PlerionClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="nodeModel"></param>
        /// <returns>Object</returns>
        public Object CreateNode(NodeModel nodeModel)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = CreateNodeWithHttpInfo(nodeModel);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="nodeModel"></param>
        /// <returns>ApiResponse of Object</returns>
        public PlerionClient.Client.ApiResponse<Object> CreateNodeWithHttpInfo(NodeModel nodeModel)
        {
            // verify the required parameter 'nodeModel' is set
            if (nodeModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'nodeModel' when calling NodesApi->CreateNode");

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = nodeModel;


            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/nodes", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="nodeModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> CreateNodeAsync(NodeModel nodeModel, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = await CreateNodeWithHttpInfoAsync(nodeModel, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="nodeModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<Object>> CreateNodeWithHttpInfoAsync(NodeModel nodeModel, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'nodeModel' is set
            if (nodeModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'nodeModel' when calling NodesApi->CreateNode");


            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = nodeModel;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/nodes", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Object</returns>
        public Object DeleteNode(Guid id)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = DeleteNodeWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object</returns>
        public PlerionClient.Client.ApiResponse<Object> DeleteNodeWithHttpInfo(Guid id)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/nodes/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> DeleteNodeAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = await DeleteNodeWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<Object>> DeleteNodeWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/nodes/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>Object</returns>
        public Object GetNode(Guid id)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = GetNodeWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <returns>ApiResponse of Object</returns>
        public PlerionClient.Client.ApiResponse<Object> GetNodeWithHttpInfo(Guid id)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/nodes/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> GetNodeAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = await GetNodeWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<Object>> GetNodeWithHttpInfoAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/nodes/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Nodes 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>List&lt;NodeModel&gt;</returns>
        public List<NodeModel> GetNodes(List<Guid> ids = default)
        {
            PlerionClient.Client.ApiResponse<List<NodeModel>> localVarResponse = GetNodesWithHttpInfo(ids);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Nodes 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <returns>ApiResponse of List&lt;NodeModel&gt;</returns>
        public PlerionClient.Client.ApiResponse<List<NodeModel>> GetNodesWithHttpInfo(List<Guid> ids = default)
        {
            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("multi", "ids", ids));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<NodeModel>>("/nodes", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNodes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Nodes 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;NodeModel&gt;</returns>
        public async System.Threading.Tasks.Task<List<NodeModel>> GetNodesAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<List<NodeModel>> localVarResponse = await GetNodesWithHttpInfoAsync(ids, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Nodes 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="ids">Optional list of Ids to filter by (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;NodeModel&gt;)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<List<NodeModel>>> GetNodesWithHttpInfoAsync(List<Guid> ids = default, System.Threading.CancellationToken cancellationToken = default)
        {

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(PlerionClient.Client.ClientUtils.ParameterToMultiMap("multi", "ids", ids));
            }


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<NodeModel>>("/nodes", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetNodes", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="nodeModel"></param>
        /// <returns>Object</returns>
        public Object UpdateNode(Guid id, NodeModel nodeModel)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = UpdateNodeWithHttpInfo(id, nodeModel);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="nodeModel"></param>
        /// <returns>ApiResponse of Object</returns>
        public PlerionClient.Client.ApiResponse<Object> UpdateNodeWithHttpInfo(Guid id, NodeModel nodeModel)
        {
            // verify the required parameter 'nodeModel' is set
            if (nodeModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'nodeModel' when calling NodesApi->UpdateNode");

            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = nodeModel;


            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/nodes/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="nodeModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<Object> UpdateNodeAsync(Guid id, NodeModel nodeModel, System.Threading.CancellationToken cancellationToken = default)
        {
            PlerionClient.Client.ApiResponse<Object> localVarResponse = await UpdateNodeWithHttpInfoAsync(id, nodeModel, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Node 
        /// </summary>
        /// <exception cref="PlerionClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="nodeModel"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<PlerionClient.Client.ApiResponse<Object>> UpdateNodeWithHttpInfoAsync(Guid id, NodeModel nodeModel, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'nodeModel' is set
            if (nodeModel == null)
                throw new PlerionClient.Client.ApiException(400, "Missing required parameter 'nodeModel' when calling NodesApi->UpdateNode");


            PlerionClient.Client.RequestOptions localVarRequestOptions = new PlerionClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = PlerionClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = PlerionClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("id", PlerionClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = nodeModel;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/nodes/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateNode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
