# coding: utf-8

"""
    Plerion

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from plerion.models.full_open_cv_camera import FullOpenCVCamera
from plerion.models.generic_params_intrinsics import GenericParamsIntrinsics
from plerion.models.open_cv_camera import OpenCVCamera
from plerion.models.pinhole_camera import PinholeCamera
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

CAMERA_ANY_OF_SCHEMAS = ["FullOpenCVCamera", "GenericParamsIntrinsics", "OpenCVCamera", "PinholeCamera"]

class Camera(BaseModel):
    """
    Camera
    """

    # data type: PinholeCamera
    anyof_schema_1_validator: Optional[PinholeCamera] = None
    # data type: OpenCVCamera
    anyof_schema_2_validator: Optional[OpenCVCamera] = None
    # data type: FullOpenCVCamera
    anyof_schema_3_validator: Optional[FullOpenCVCamera] = None
    # data type: GenericParamsIntrinsics
    anyof_schema_4_validator: Optional[GenericParamsIntrinsics] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "FullOpenCVCamera", "GenericParamsIntrinsics", "OpenCVCamera", "PinholeCamera" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = Camera.model_construct()
        error_messages = []
        # validate data type: PinholeCamera
        if not isinstance(v, PinholeCamera):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PinholeCamera`")
        else:
            return v

        # validate data type: OpenCVCamera
        if not isinstance(v, OpenCVCamera):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OpenCVCamera`")
        else:
            return v

        # validate data type: FullOpenCVCamera
        if not isinstance(v, FullOpenCVCamera):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FullOpenCVCamera`")
        else:
            return v

        # validate data type: GenericParamsIntrinsics
        if not isinstance(v, GenericParamsIntrinsics):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GenericParamsIntrinsics`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in Camera with anyOf schemas: FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[PinholeCamera] = None
        try:
            instance.actual_instance = PinholeCamera.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[OpenCVCamera] = None
        try:
            instance.actual_instance = OpenCVCamera.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[FullOpenCVCamera] = None
        try:
            instance.actual_instance = FullOpenCVCamera.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[GenericParamsIntrinsics] = None
        try:
            instance.actual_instance = GenericParamsIntrinsics.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Camera with anyOf schemas: FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


