# coding: utf-8

"""
    Plerion

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from plerion.models.full_open_cv_camera import FullOpenCVCamera
from plerion.models.generic_params_intrinsics import GenericParamsIntrinsics
from plerion.models.open_cv_camera import OpenCVCamera
from plerion.models.pinhole_camera import PinholeCamera
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

INTRINSICS_ONE_OF_SCHEMAS = ["FullOpenCVCamera", "GenericParamsIntrinsics", "OpenCVCamera", "PinholeCamera"]

class Intrinsics(BaseModel):
    """
    Intrinsics
    """
    # data type: PinholeCamera
    oneof_schema_1_validator: Optional[PinholeCamera] = None
    # data type: OpenCVCamera
    oneof_schema_2_validator: Optional[OpenCVCamera] = None
    # data type: FullOpenCVCamera
    oneof_schema_3_validator: Optional[FullOpenCVCamera] = None
    # data type: GenericParamsIntrinsics
    oneof_schema_4_validator: Optional[GenericParamsIntrinsics] = None
    actual_instance: Optional[Union[FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera]] = None
    one_of_schemas: Set[str] = { "FullOpenCVCamera", "GenericParamsIntrinsics", "OpenCVCamera", "PinholeCamera" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Intrinsics.model_construct()
        error_messages = []
        match = 0
        # validate data type: PinholeCamera
        if not isinstance(v, PinholeCamera):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PinholeCamera`")
        else:
            match += 1
        # validate data type: OpenCVCamera
        if not isinstance(v, OpenCVCamera):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OpenCVCamera`")
        else:
            match += 1
        # validate data type: FullOpenCVCamera
        if not isinstance(v, FullOpenCVCamera):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FullOpenCVCamera`")
        else:
            match += 1
        # validate data type: GenericParamsIntrinsics
        if not isinstance(v, GenericParamsIntrinsics):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GenericParamsIntrinsics`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Intrinsics with oneOf schemas: FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Intrinsics with oneOf schemas: FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PinholeCamera
        try:
            instance.actual_instance = PinholeCamera.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OpenCVCamera
        try:
            instance.actual_instance = OpenCVCamera.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FullOpenCVCamera
        try:
            instance.actual_instance = FullOpenCVCamera.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GenericParamsIntrinsics
        try:
            instance.actual_instance = GenericParamsIntrinsics.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Intrinsics with oneOf schemas: FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Intrinsics with oneOf schemas: FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FullOpenCVCamera, GenericParamsIntrinsics, OpenCVCamera, PinholeCamera]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


