# coding: utf-8

"""
    Plerion

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class LocalizationMapRead(BaseModel):
    """
    LocalizationMapRead
    """ # noqa: E501
    reconstruction_id: UUID
    id: UUID
    rotation_y: Union[StrictFloat, StrictInt]
    position_x: Union[StrictFloat, StrictInt]
    position_y: Union[StrictFloat, StrictInt]
    position_z: Union[StrictFloat, StrictInt]
    rotation_x: Union[StrictFloat, StrictInt]
    updated_at: datetime
    rotation_z: Union[StrictFloat, StrictInt]
    rotation_w: Union[StrictFloat, StrictInt]
    color: StrictInt
    created_at: datetime
    active: StrictBool
    lighting: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["reconstruction_id", "id", "rotation_y", "position_x", "position_y", "position_z", "rotation_x", "updated_at", "rotation_z", "rotation_w", "color", "created_at", "active", "lighting", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LocalizationMapRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if lighting (nullable) is None
        # and model_fields_set contains the field
        if self.lighting is None and "lighting" in self.model_fields_set:
            _dict['lighting'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LocalizationMapRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reconstruction_id": obj.get("reconstruction_id"),
            "id": obj.get("id"),
            "rotation_y": obj.get("rotation_y"),
            "position_x": obj.get("position_x"),
            "position_y": obj.get("position_y"),
            "position_z": obj.get("position_z"),
            "rotation_x": obj.get("rotation_x"),
            "updated_at": obj.get("updated_at"),
            "rotation_z": obj.get("rotation_z"),
            "rotation_w": obj.get("rotation_w"),
            "color": obj.get("color"),
            "created_at": obj.get("created_at"),
            "active": obj.get("active"),
            "lighting": obj.get("lighting"),
            "name": obj.get("name")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


