# coding: utf-8

"""
    Plerion

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ReconstructionOptions(BaseModel):
    """
    ReconstructionOptions
    """ # noqa: E501
    random_seed: Optional[StrictInt] = None
    single_threaded: Optional[StrictBool] = None
    neighbors_count: Optional[StrictInt] = None
    max_keypoints_per_image: Optional[StrictInt] = None
    ransac_max_error: Optional[Union[StrictFloat, StrictInt]] = None
    ransac_min_inlier_ratio: Optional[Union[StrictFloat, StrictInt]] = None
    use_prior_position: Optional[StrictBool] = None
    rig_verification: Optional[StrictBool] = None
    triangulation_minimum_angle: Optional[Union[StrictFloat, StrictInt]] = None
    triangulation_complete_max_reprojection_error: Optional[Union[StrictFloat, StrictInt]] = None
    triangulation_merge_max_reprojection_error: Optional[Union[StrictFloat, StrictInt]] = None
    mapper_filter_max_reprojection_error: Optional[Union[StrictFloat, StrictInt]] = None
    bundle_adjustment_refine_sensor_from_rig: Optional[StrictBool] = None
    bundle_adjustment_refine_focal_length: Optional[StrictBool] = None
    bundle_adjustment_refine_principal_point: Optional[StrictBool] = None
    bundle_adjustment_refine_additional_params: Optional[StrictBool] = None
    compression_opq_number_of_subvectors: Optional[StrictInt] = None
    compression_opq_number_bits_per_subvector: Optional[StrictInt] = None
    compression_opq_number_of_training_iterations: Optional[StrictInt] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["random_seed", "single_threaded", "neighbors_count", "max_keypoints_per_image", "ransac_max_error", "ransac_min_inlier_ratio", "use_prior_position", "rig_verification", "triangulation_minimum_angle", "triangulation_complete_max_reprojection_error", "triangulation_merge_max_reprojection_error", "mapper_filter_max_reprojection_error", "bundle_adjustment_refine_sensor_from_rig", "bundle_adjustment_refine_focal_length", "bundle_adjustment_refine_principal_point", "bundle_adjustment_refine_additional_params", "compression_opq_number_of_subvectors", "compression_opq_number_bits_per_subvector", "compression_opq_number_of_training_iterations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReconstructionOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if random_seed (nullable) is None
        # and model_fields_set contains the field
        if self.random_seed is None and "random_seed" in self.model_fields_set:
            _dict['random_seed'] = None

        # set to None if single_threaded (nullable) is None
        # and model_fields_set contains the field
        if self.single_threaded is None and "single_threaded" in self.model_fields_set:
            _dict['single_threaded'] = None

        # set to None if neighbors_count (nullable) is None
        # and model_fields_set contains the field
        if self.neighbors_count is None and "neighbors_count" in self.model_fields_set:
            _dict['neighbors_count'] = None

        # set to None if max_keypoints_per_image (nullable) is None
        # and model_fields_set contains the field
        if self.max_keypoints_per_image is None and "max_keypoints_per_image" in self.model_fields_set:
            _dict['max_keypoints_per_image'] = None

        # set to None if ransac_max_error (nullable) is None
        # and model_fields_set contains the field
        if self.ransac_max_error is None and "ransac_max_error" in self.model_fields_set:
            _dict['ransac_max_error'] = None

        # set to None if ransac_min_inlier_ratio (nullable) is None
        # and model_fields_set contains the field
        if self.ransac_min_inlier_ratio is None and "ransac_min_inlier_ratio" in self.model_fields_set:
            _dict['ransac_min_inlier_ratio'] = None

        # set to None if use_prior_position (nullable) is None
        # and model_fields_set contains the field
        if self.use_prior_position is None and "use_prior_position" in self.model_fields_set:
            _dict['use_prior_position'] = None

        # set to None if rig_verification (nullable) is None
        # and model_fields_set contains the field
        if self.rig_verification is None and "rig_verification" in self.model_fields_set:
            _dict['rig_verification'] = None

        # set to None if triangulation_minimum_angle (nullable) is None
        # and model_fields_set contains the field
        if self.triangulation_minimum_angle is None and "triangulation_minimum_angle" in self.model_fields_set:
            _dict['triangulation_minimum_angle'] = None

        # set to None if triangulation_complete_max_reprojection_error (nullable) is None
        # and model_fields_set contains the field
        if self.triangulation_complete_max_reprojection_error is None and "triangulation_complete_max_reprojection_error" in self.model_fields_set:
            _dict['triangulation_complete_max_reprojection_error'] = None

        # set to None if triangulation_merge_max_reprojection_error (nullable) is None
        # and model_fields_set contains the field
        if self.triangulation_merge_max_reprojection_error is None and "triangulation_merge_max_reprojection_error" in self.model_fields_set:
            _dict['triangulation_merge_max_reprojection_error'] = None

        # set to None if mapper_filter_max_reprojection_error (nullable) is None
        # and model_fields_set contains the field
        if self.mapper_filter_max_reprojection_error is None and "mapper_filter_max_reprojection_error" in self.model_fields_set:
            _dict['mapper_filter_max_reprojection_error'] = None

        # set to None if bundle_adjustment_refine_sensor_from_rig (nullable) is None
        # and model_fields_set contains the field
        if self.bundle_adjustment_refine_sensor_from_rig is None and "bundle_adjustment_refine_sensor_from_rig" in self.model_fields_set:
            _dict['bundle_adjustment_refine_sensor_from_rig'] = None

        # set to None if bundle_adjustment_refine_focal_length (nullable) is None
        # and model_fields_set contains the field
        if self.bundle_adjustment_refine_focal_length is None and "bundle_adjustment_refine_focal_length" in self.model_fields_set:
            _dict['bundle_adjustment_refine_focal_length'] = None

        # set to None if bundle_adjustment_refine_principal_point (nullable) is None
        # and model_fields_set contains the field
        if self.bundle_adjustment_refine_principal_point is None and "bundle_adjustment_refine_principal_point" in self.model_fields_set:
            _dict['bundle_adjustment_refine_principal_point'] = None

        # set to None if bundle_adjustment_refine_additional_params (nullable) is None
        # and model_fields_set contains the field
        if self.bundle_adjustment_refine_additional_params is None and "bundle_adjustment_refine_additional_params" in self.model_fields_set:
            _dict['bundle_adjustment_refine_additional_params'] = None

        # set to None if compression_opq_number_of_subvectors (nullable) is None
        # and model_fields_set contains the field
        if self.compression_opq_number_of_subvectors is None and "compression_opq_number_of_subvectors" in self.model_fields_set:
            _dict['compression_opq_number_of_subvectors'] = None

        # set to None if compression_opq_number_bits_per_subvector (nullable) is None
        # and model_fields_set contains the field
        if self.compression_opq_number_bits_per_subvector is None and "compression_opq_number_bits_per_subvector" in self.model_fields_set:
            _dict['compression_opq_number_bits_per_subvector'] = None

        # set to None if compression_opq_number_of_training_iterations (nullable) is None
        # and model_fields_set contains the field
        if self.compression_opq_number_of_training_iterations is None and "compression_opq_number_of_training_iterations" in self.model_fields_set:
            _dict['compression_opq_number_of_training_iterations'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReconstructionOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "random_seed": obj.get("random_seed"),
            "single_threaded": obj.get("single_threaded"),
            "neighbors_count": obj.get("neighbors_count"),
            "max_keypoints_per_image": obj.get("max_keypoints_per_image"),
            "ransac_max_error": obj.get("ransac_max_error"),
            "ransac_min_inlier_ratio": obj.get("ransac_min_inlier_ratio"),
            "use_prior_position": obj.get("use_prior_position"),
            "rig_verification": obj.get("rig_verification"),
            "triangulation_minimum_angle": obj.get("triangulation_minimum_angle"),
            "triangulation_complete_max_reprojection_error": obj.get("triangulation_complete_max_reprojection_error"),
            "triangulation_merge_max_reprojection_error": obj.get("triangulation_merge_max_reprojection_error"),
            "mapper_filter_max_reprojection_error": obj.get("mapper_filter_max_reprojection_error"),
            "bundle_adjustment_refine_sensor_from_rig": obj.get("bundle_adjustment_refine_sensor_from_rig"),
            "bundle_adjustment_refine_focal_length": obj.get("bundle_adjustment_refine_focal_length"),
            "bundle_adjustment_refine_principal_point": obj.get("bundle_adjustment_refine_principal_point"),
            "bundle_adjustment_refine_additional_params": obj.get("bundle_adjustment_refine_additional_params"),
            "compression_opq_number_of_subvectors": obj.get("compression_opq_number_of_subvectors"),
            "compression_opq_number_bits_per_subvector": obj.get("compression_opq_number_bits_per_subvector"),
            "compression_opq_number_of_training_iterations": obj.get("compression_opq_number_of_training_iterations")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


