# coding: utf-8

# flake8: noqa
"""
    Database Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from plerion_client.models.body_create_database import BodyCreateDatabase
    from plerion_client.models.http_validation_error import HTTPValidationError
    from plerion_client.models.validation_error import ValidationError
    from plerion_client.models.validation_error_loc_inner import ValidationErrorLocInner
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from plerion_client.models.body_create_database import BodyCreateDatabase
from plerion_client.models.http_validation_error import HTTPValidationError
from plerion_client.models.validation_error import ValidationError
from plerion_client.models.validation_error_loc_inner import ValidationErrorLocInner

""",
            name=__name__,
            doc=__doc__,
        )
    )
