environment:
  - plerion/core

config:
  aws:region: us-east-1
  plerion_infra:github-branch: feature/database-manager
  plerion_infra:deploy-cloudbeaver: true
  plerion_infra:deploy-tailscale-beacon: true
  plerion_infra:deploy-auth-gateway: true
  plerion_infra:deploy-database-manager: true
