/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    // fuck
    /// <summary>
    /// CaptureSessionCreate
    /// </summary>
    [DataContract(Name = "CaptureSessionCreate")]
    public partial class CaptureSessionCreate
    {

        /// <summary>
        /// Gets or Sets DeviceType
        /// </summary>

        [DataMember(Name = "device_type", IsRequired = true, EmitDefaultValue = true)]
        public DeviceType DeviceType
        {
            get{ return _DeviceType;}
            set
            {
                _DeviceType = value;
                _flagDeviceType = true;
            }
        }
        private DeviceType _DeviceType;
        private bool _flagDeviceType;

        /// <summary>
        /// Returns false as DeviceType should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDeviceType()
        {
            return _flagDeviceType;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureSessionCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CaptureSessionCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureSessionCreate" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="deviceType">deviceType (required).</param>
        /// <param name="filename">filename (required).</param>
        public CaptureSessionCreate(DeviceType deviceType, string filename)
        {
            this.DeviceType = deviceType;
            // to ensure "filename" is required (not null)
            if (filename == null)
            {
                throw new ArgumentNullException("filename is a required property for CaptureSessionCreate and cannot be null");
            }
            this.Filename = filename;
        }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", IsRequired = true, EmitDefaultValue = true)]
        public string Filename
        {
            get{ return _Filename;}
            set
            {
                _Filename = value;
                _flagFilename = true;
            }
        }
        private string _Filename;
        private bool _flagFilename;

        /// <summary>
        /// Returns false as Filename should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeFilename()
        {
            return _flagFilename;
        }
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = true)]
        public Guid? Id
        {
            get{ return _Id;}
            set
            {
                _Id = value;
                _flagId = true;
            }
        }
        private Guid? _Id;
        private bool _flagId;

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return _flagId;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CaptureSessionCreate {\n");
            sb.Append("  DeviceType: ").Append(DeviceType).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
