/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    // fuck
    /// <summary>
    /// CaptureSessionBatchUpdate
    /// </summary>
    [DataContract(Name = "CaptureSessionBatchUpdate")]
    public partial class CaptureSessionBatchUpdate
    {

        /// <summary>
        /// Gets or Sets DeviceType
        /// </summary>

        [DataMember(Name = "device_type", EmitDefaultValue = true)]
        public DeviceType? DeviceType
        {
            get{ return _DeviceType;}
            set
            {
                _DeviceType = value;
                _flagDeviceType = true;
            }
        }
        private DeviceType? _DeviceType;
        private bool _flagDeviceType;

        /// <summary>
        /// Returns false as DeviceType should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDeviceType()
        {
            return _flagDeviceType;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureSessionBatchUpdate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CaptureSessionBatchUpdate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CaptureSessionBatchUpdate" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="deviceType">deviceType.</param>
        /// <param name="filename">filename.</param>
        public CaptureSessionBatchUpdate(Guid id)
        {
            this.Id = id;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id
        {
            get{ return _Id;}
            set
            {
                _Id = value;
                _flagId = true;
            }
        }
        private Guid _Id;
        private bool _flagId;

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return _flagId;
        }
        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", EmitDefaultValue = true)]
        public string Filename
        {
            get{ return _Filename;}
            set
            {
                _Filename = value;
                _flagFilename = true;
            }
        }
        private string _Filename;
        private bool _flagFilename;

        /// <summary>
        /// Returns false as Filename should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeFilename()
        {
            return _flagFilename;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CaptureSessionBatchUpdate {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  DeviceType: ").Append(DeviceType).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
