/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    // fuck
    /// <summary>
    /// GenericParamsIntrinsics
    /// </summary>
    [DataContract(Name = "GenericParamsIntrinsics")]
    public partial class GenericParamsIntrinsics
    {
        /// <summary>
        /// Defines Model
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ModelEnum
        {
            /// <summary>
            /// Enum GENERIC for value: GENERIC
            /// </summary>
            [EnumMember(Value = "GENERIC")]
            GENERIC = 1
        }



        /// <summary>
        /// Gets or Sets Model
        /// </summary>

        [DataMember(Name = "model", IsRequired = true, EmitDefaultValue = true)]
        public ModelEnum Model
        {
            get{ return _Model;}
            set
            {
                _Model = value;
                _flagModel = true;
            }
        }
        private ModelEnum _Model;
        private bool _flagModel;

        /// <summary>
        /// Returns false as Model should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeModel()
        {
            return _flagModel;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="GenericParamsIntrinsics" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GenericParamsIntrinsics() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GenericParamsIntrinsics" /> class.
        /// </summary>
        /// <param name="model">model (required).</param>
        /// <param name="width">width (required).</param>
        /// <param name="height">height (required).</param>
        /// <param name="varParams">varParams (required).</param>
        public GenericParamsIntrinsics(ModelEnum model, int width, int height, List<double> varParams)
        {
            this.Model = model;
            this.Width = width;
            this.Height = height;
            // to ensure "varParams" is required (not null)
            if (varParams == null)
            {
                throw new ArgumentNullException("varParams is a required property for GenericParamsIntrinsics and cannot be null");
            }
            this.Params = varParams;
        }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "width", IsRequired = true, EmitDefaultValue = true)]
        public int Width
        {
            get{ return _Width;}
            set
            {
                _Width = value;
                _flagWidth = true;
            }
        }
        private int _Width;
        private bool _flagWidth;

        /// <summary>
        /// Returns false as Width should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeWidth()
        {
            return _flagWidth;
        }
        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", IsRequired = true, EmitDefaultValue = true)]
        public int Height
        {
            get{ return _Height;}
            set
            {
                _Height = value;
                _flagHeight = true;
            }
        }
        private int _Height;
        private bool _flagHeight;

        /// <summary>
        /// Returns false as Height should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeHeight()
        {
            return _flagHeight;
        }
        /// <summary>
        /// Gets or Sets Params
        /// </summary>
        [DataMember(Name = "params", IsRequired = true, EmitDefaultValue = true)]
        public List<double> Params
        {
            get{ return _Params;}
            set
            {
                _Params = value;
                _flagParams = true;
            }
        }
        private List<double> _Params;
        private bool _flagParams;

        /// <summary>
        /// Returns false as Params should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeParams()
        {
            return _flagParams;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GenericParamsIntrinsics {\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Params: ").Append(Params).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
