/*
 * Plerion
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    // fuck
    /// <summary>
    /// MapLocalizationInput
    /// </summary>
    [DataContract(Name = "MapLocalization-Input")]
    public partial class MapLocalizationInput
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MapLocalizationInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MapLocalizationInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MapLocalizationInput" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="transform">transform (required).</param>
        /// <param name="mapTransform">mapTransform (required).</param>
        public MapLocalizationInput(Guid id, Transform transform, Transform mapTransform)
        {
            this.Id = id;
            // to ensure "transform" is required (not null)
            if (transform == null)
            {
                throw new ArgumentNullException("transform is a required property for MapLocalizationInput and cannot be null");
            }
            this.Transform = transform;
            // to ensure "mapTransform" is required (not null)
            if (mapTransform == null)
            {
                throw new ArgumentNullException("mapTransform is a required property for MapLocalizationInput and cannot be null");
            }
            this.MapTransform = mapTransform;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id
        {
            get{ return _Id;}
            set
            {
                _Id = value;
                _flagId = true;
            }
        }
        private Guid _Id;
        private bool _flagId;

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return _flagId;
        }
        /// <summary>
        /// Gets or Sets Transform
        /// </summary>
        [DataMember(Name = "transform", IsRequired = true, EmitDefaultValue = true)]
        public Transform Transform
        {
            get{ return _Transform;}
            set
            {
                _Transform = value;
                _flagTransform = true;
            }
        }
        private Transform _Transform;
        private bool _flagTransform;

        /// <summary>
        /// Returns false as Transform should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTransform()
        {
            return _flagTransform;
        }
        /// <summary>
        /// Gets or Sets MapTransform
        /// </summary>
        [DataMember(Name = "map_transform", IsRequired = true, EmitDefaultValue = true)]
        public Transform MapTransform
        {
            get{ return _MapTransform;}
            set
            {
                _MapTransform = value;
                _flagMapTransform = true;
            }
        }
        private Transform _MapTransform;
        private bool _flagMapTransform;

        /// <summary>
        /// Returns false as MapTransform should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMapTransform()
        {
            return _flagMapTransform;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MapLocalizationInput {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Transform: ").Append(Transform).Append("\n");
            sb.Append("  MapTransform: ").Append(MapTransform).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
