name: build-and-push-image
description: Build and push a Docker image to ECR, using Pulumi to get re
inputs:
  service:
    required: true
    description: "Service name"
  image_tag:
    required: true
    description: "Immutable image tag"
  build-context:
    required: true
    description: "Docker build context path for this service"
  stack:
    required: true
    description: "Pulumi stack name"
outputs:
  repo_digest:
    value: ${{ steps.meta.outputs.repo_digest }}
    description: "The digest of the Docker image"
runs:
  using: composite
  steps:
    - name: Download Pulumi outputs 
      uses: actions/download-artifact@v4
      with:
        name: pulumi-outputs
        path: pulumi-outs
          
    - name: Extract per-service outputs
      id: pulumi-outputs
      shell: bash
      run: |
        set -euo pipefail
        FILE="${{ inputs.stack }}.json"
        SERVICE="${{ inputs.service }}"
        echo "repo-url=$(jq -e -r --arg svc "$SERVICE" '.[$svc + "-image-repo-url"]' "$FILE")" >> $GITHUB_OUTPUT
        echo "role=$(jq -e -r --arg svc "$SERVICE" '.[$svc + "-image-repo-role-arn"]' "$FILE")" >> $GITHUB_OUTPUT
        echo "region=$(sed -n 's#.*\.dkr\.ecr\.\([^.]*\)\.amazonaws\.com/.*#\1#p' <<<"$REPO_URL")" >> $GITHUB_OUTPUT

    - name: Authenticate with AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.pulumi-outputs.outputs.role }}
        aws-region:     ${{ steps.pulumi-outputs.outputs.region }}

    - name: Authenticate with ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push image
      shell: bash
      run: |
        set -euo pipefail
        IMAGE="${{ steps.pulumi-outputs.outputs.repo_url }}:${{ inputs.image_tag }}"
        echo "Building $IMAGE from ${{ inputs.build-context }}"
        docker build -t "$IMAGE" "${{ inputs.build-context }}"
        docker push "$IMAGE"
        echo "repo_digest=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE")" >> $GITHUB_OUTPUT

    - name: Set outputs
      id: meta
      shell: bash
      run: |
        echo "repo_digest=${{ steps.build.outputs.repo_digest }}" >> $GITHUB_OUTPUT

