/*
 * Plerion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    /// <summary>
    /// BodyUpsertNode
    /// </summary>
    [DataContract(Name = "Body_upsert_node")]
    public partial class BodyUpsertNode
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyUpsertNode" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BodyUpsertNode() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyUpsertNode" /> class.
        /// </summary>
        /// <param name="nodes">nodes (required).</param>
        public BodyUpsertNode(List<NodeModel> nodes = default)
        {
            // to ensure "nodes" is required (not null)
            if (nodes == null)
            {
                throw new ArgumentNullException("nodes is a required property for BodyUpsertNode and cannot be null");
            }
            this.Nodes = nodes;
        }

        /// <summary>
        /// Gets or Sets Nodes
        /// </summary>
        [DataMember(Name = "nodes", IsRequired = true, EmitDefaultValue = true)]
        public List<NodeModel> Nodes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BodyUpsertNode {\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
