/*
 * Plerion API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = PlerionClient.Client.FileParameter;
using OpenAPIDateConverter = PlerionClient.Client.OpenAPIDateConverter;

namespace PlerionClient.Model
{
    /// <summary>
    /// BodyDeleteLayers
    /// </summary>
    [DataContract(Name = "Body_delete_layers")]
    public partial class BodyDeleteLayers
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyDeleteLayers" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BodyDeleteLayers() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BodyDeleteLayers" /> class.
        /// </summary>
        /// <param name="ids">ids (required).</param>
        public BodyDeleteLayers(List<Guid> ids = default)
        {
            // to ensure "ids" is required (not null)
            if (ids == null)
            {
                throw new ArgumentNullException("ids is a required property for BodyDeleteLayers and cannot be null");
            }
            this.Ids = ids;
        }

        /// <summary>
        /// Gets or Sets Ids
        /// </summary>
        [DataMember(Name = "ids", IsRequired = true, EmitDefaultValue = true)]
        public List<Guid> Ids { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BodyDeleteLayers {\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
